[tool.poetry]
name = "vmm_manager_ansible_collection"
version = "0.0.1"
description = "Ansible Collection to support vmm_manager application on Ansible codes."
authors = ["Estevão Costa <ecosta@mpes.mp.br>"]

license = "MIT"
readme = "README.md"

homepage = "https://github.com/MP-ES/vmm_manager_ansible_collection"
repository = "https://github.com/MP-ES/vmm_manager_ansible_collection"
documentation = "https://github.com/MP-ES/vmm_manager_ansible_collection"

keywords = ["IaC", "scvmm", "vmm_manager", "vmm_manager_ansible_collection"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: System Administrators",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Systems Administration",
]

[tool.poetry.dependencies]
python = "^3.7"
ansible = "^2.9"
vmm-manager = ">=0.1.0b2"

[tool.poetry.dev-dependencies]
pylint = "^2.5"
pylint-quotes = "^0.2"
autopep8 = "^1.5"
rope = "^0.17"
pytest = "^5.4"
pytest-mock = "^3.1"
Faker = "^4.1"

[build-system]
requires = ["poetry^1.0"]
build-backend = "poetry.masonry.api"
